config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#home'


  # Ressources Promotions
  #
  # Contrôleur : PromotionsController (app/controllers/promotions_controller)
  #
  # Routes :
  #
  resources :promotions do
    member do
      put 'close', to: 'promotions#close'     # Route de clôture de promotion
    end
  end


  # Ressources Formations
  #
  # Contrôleur : FormationsController (app/controllers/formations_controller)
  #
  # Routes :
  #
  resources :formations do
    member do
      get 'next', to: 'formations#next'             # Route pour sélectionner les étudiants à faire passer à la promotion suivante
      post 'transfert', to: 'formations#transfert'  # Route réalisant le transfert des étudiants à la promotion suivante
    end
  end


  # Ressources Etudiants
  #
  # Contrôleur : EtudiantsController (app/controllers/etudiants_controller)
  #
  # Routes :
  #       etudiants GET    /etudiants(.:format)                                    etudiants#index
  #                 POST   /etudiants(.:format)                                    etudiants#create
  #    new_etudiant GET    /etudiants/new(.:format)                                etudiants#new
  #   edit_etudiant GET    /etudiants/:id/edit(.:format)                           etudiants#edit
  #        etudiant GET    /etudiants/:id(.:format)                                etudiants#show
  #                 PATCH  /etudiants/:id(.:format)                                etudiants#update
  #                 PUT    /etudiants/:id(.:format)                                etudiants#update
  #                 DELETE /etudiants/:id(.:format)                                etudiants#destroy
  #
  resources :etudiants


  # Confiugration des routes pour Devise
  #
  # Documentation : https://github.com/heartcombo/devise#
  #
  # 3 modèles :
  #   - Etudiants                     :etudiants
  #   - Tuteurs universitaires        :tuteur_universitaires
  #   - Responsable des stages        :responsable_stages
  #
  devise_for :etudiants,
             path: '/auth',                                 # Préfixage des routes avec '/auth'
             controllers: {
               # Surcharge du contrôleur de registration de devise par le contrôleur Etudiants::RegistrationsController
               registrations: "etudiants/registrations"
             }

  devise_scope :etudiant do
    # Génération d'une route permettant l'inscription des étudiants
    get '4d6a8d14-ef57-4da8-908d-5b3388bfdf48/sign_up', to: 'etudiants/registrations#new', :as => 'guid_etudiant_sign_up'
  end


  devise_for :tuteur_universitaires, controllers: {
    registrations: "tuteur_universitaires/registrations"
  }

  devise_scope :tuteur_universitaire do
    # get '/sign_in', to: 'devise/sessions#new'
    get 'f5506526-0a7d-40af-a39f-e456e5991564/sign_up', to: 'tuteur_universitaires/registrations#new'
  end


  devise_for :responsable_stages, controllers: {
    registrations: "responsable_stages/registrations"
  }

  devise_scope :responsable_stage do
    # get '/sign_in', to: 'devise/sessions#new'
    get '505cccad-922c-4251-bae6-55c5f91df05b/sign_up', to: 'responsable_stages/registrations#new'
  end


  # Require a root to for devise
  root to: 'static#index'

  get '/static', to: 'static#index'
  post '/fiche_stages/csend', to: 'fiche_stages#csend'
  patch '/fiche_stages/:id/usend', to: 'fiche_stages#usend', as: :fiche_stages_usend
  get '/fiche_stages/:id/validate', to: 'fiche_stages#validate', as: :fiche_stages_validate

  patch '/fiche_stages/:id/vyes', to: 'fiche_stages#vyes', as: :fiche_stages_vyes
  patch '/fiche_stages/:id/vno', to: 'fiche_stages#vno', as: :fiche_stages_vno

  resources :fiche_stages, except: [:destroy, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html





  # Contrôleur EntreprisesController
  resources :entreprises

  # Contrôleur TuteurUniversitaireController
  resources :tuteur_universitaires



  # Contrôleur StaticController
  get '/static', to: 'static#index'

  get '/evaluation', to: 'evaluations#evaluation'
  get '/evaluationtemplate', to: 'evaluations#template'
  get '/notationtemplate', to: 'notations#template'
  post '/evaluation/save/(:id)', to: 'evaluations#save'
  get '/evaluation/edit/(:id)', to: 'evaluations#editEvaluation'
  get '/evaluation/view/(:id)', to: 'evaluations#viewEvaluation'
  get '/tableaudebord', to: 'tableau_de_bord#tableauDeBord'
  get '/menuetudiant', to: 'menu#menuEtudiant'
  get '/menurespstage', to: 'menu#menuRespStage'
  get '/menu', to: 'menu#redirection'
  get '/notation/(:id)', to: 'notations#notation'
  get '/notation/view/(:id)', to: 'notations#viewNotation'
  post '/notation/save', to: 'notations#saveNotation'
  get '/evolution', to: 'evolutions#evolution'
  get '/statistiques', to: 'statistiques#statistiques'
  get '/tableEtudiant', to: 'table_etudiant#tableEtudiant'
  resources :ge_formats
  resources :notation_formats
end

app/models/notation_formats.rb
class NotationFormats < ApplicationRecord

end

app/controllers/notation_formats_controller.rb
class NotationFormatsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    redirect_to action: "show", id: NotationFormats.first.nil? ? 0 : NotationFormats.last.id
  end

  def new
    redirect_to action: "show", id: 0
  end

  def show
    if !responsable_stage_signed_in?
      redirect_to("/")
    else
      @notation_id = params[:id]
      @notation_formats = if NotationFormats.exists?(params[:id])
                            JSON.parse NotationFormats.find(params[:id]).contenu.to_s
                          else
                            @notation_id = "new"
                            JSON.parse '{"bareme":[]}'
                          end
      @notation_ids = NotationFormats.ids
    end
  end

  def create
    @NotationFormats_to_save = NotationFormats.new
    @NotationFormats_to_save.contenu = params[:notation_format].to_s.gsub("=>", ":")

    if @NotationFormats_to_save.save
      redirect_to @NotationFormats_to_save
    end
  end
end

app/views/notation_formats/show.html.erb
<%= stylesheet_link_tag "evaluation" %>
<p style="display:none" id="mydata"><%= @notation_formats.to_json %></p>

<div class="bandeauSuperieur d-flex justify-content-center">
  <span class="mx-4 uppercase font-bold"><%= @notation_id != "new" ? "Edition de la fiche d'évaluation n°" + @notation_id : "Création de fiche de notation" %></span>
</div>

<div class="d-flex justify-content-center align-items-center drop py-3">
  <label class="mx-2" for="ver">Charger une version : </label>
  <select class="dropdown btn-sm px-3 mx-2 btn-round" name="Editer une version" required id="ver" style="width: 20%;">
    <option value="" disabled selected>Version</option>
    <% for option in @notation_ids %>
      <option class="dropdown-item" <%= @notation_id.to_s == option.to_s ? "selected" : "" %>><%= option %></option>
    <% end %>
  </select>
  <p class="my-2 mx-4">OU</p>
  <%= button_to "Creer un nouveau formulaire", new_notation_format_path, method: :get, class: "btn btn-round btn-sm px-3 mx-2" %>
</div>

<div class="m-4 pt-3">
  <% if @notation_id != "new" %>
    <div class="section">
      <div class="block">
        <div style="color: #181552">
          Une édition sur une fiche déjà existante entrainera une nouvelle version en base de donnée.
        </div>
      </div>
    </div>
  <% end %>
  <div class="section">
    <div class="block">
      <div class="sous-titre">
        <span class="uppercase font-bold text-darkgrey">Note de l'entreprise</span>
      </div>

      <table class="table" style="box-shadow: none">
        <thead>
          <tr id="libelles" style="background-color: white">

          </tr>
        </thead>
        <tbody>
          <tr id="values">

          </tr>
        </tbody>
      </table>
      <button type="button" class="btn btn-round btn-sm px-3 mt-2" id="add_bareme" style="float:right">+ Ajouter un choix</button>
    </div>
  </div>

  <div class="section">
    <div class="block">
      <div class="sous-titre-com">
        <div>
          <span class="uppercase font-bold text-darkgrey" style="float: left">Espace de commentaire</span>
          <div class="form-check form-switch" >
            <input class="form-check-input toggle" type="checkbox" id="commentaire" style="float:right"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center py-2 pb-4">
  <button id="submit_button" class="btn btn-round" value="<%= notation_formats_path %>">Soumettre</button>
</div>

<%= javascript_pack_tag 'notation_formats' %>