config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#home'


  # Ressources Promotions
  #
  # Contrôleur : PromotionsController (app/controllers/promotions_controller)
  #
  # Routes :
  #
  resources :promotions do
    member do
      put 'close', to: 'promotions#close'     # Route de clôture de promotion
    end
  end


  # Ressources Formations
  #
  # Contrôleur : FormationsController (app/controllers/formations_controller)
  #
  # Routes :
  #
  resources :formations do
    member do
      get 'next', to: 'formations#next'             # Route pour sélectionner les étudiants à faire passer à la promotion suivante
      post 'transfert', to: 'formations#transfert'  # Route réalisant le transfert des étudiants à la promotion suivante
    end
  end


  # Ressources Etudiants
  #
  # Contrôleur : EtudiantsController (app/controllers/etudiants_controller)
  #
  # Routes :
  #       etudiants GET    /etudiants(.:format)                                    etudiants#index
  #                 POST   /etudiants(.:format)                                    etudiants#create
  #    new_etudiant GET    /etudiants/new(.:format)                                etudiants#new
  #   edit_etudiant GET    /etudiants/:id/edit(.:format)                           etudiants#edit
  #        etudiant GET    /etudiants/:id(.:format)                                etudiants#show
  #                 PATCH  /etudiants/:id(.:format)                                etudiants#update
  #                 PUT    /etudiants/:id(.:format)                                etudiants#update
  #                 DELETE /etudiants/:id(.:format)                                etudiants#destroy
  #
  resources :etudiants


  # Confiugration des routes pour Devise
  #
  # Documentation : https://github.com/heartcombo/devise#
  #
  # 3 modèles :
  #   - Etudiants                     :etudiants
  #   - Tuteurs universitaires        :tuteur_universitaires
  #   - Responsable des stages        :responsable_stages
  #
  devise_for :etudiants,
             path: '/auth',                                 # Préfixage des routes avec '/auth'
             controllers: {
               # Surcharge du contrôleur de registration de devise par le contrôleur Etudiants::RegistrationsController
               registrations: "etudiants/registrations"
             }

  devise_scope :etudiant do
    # Génération d'une route permettant l'inscription des étudiants
    get '4d6a8d14-ef57-4da8-908d-5b3388bfdf48/sign_up', to: 'etudiants/registrations#new', :as => 'guid_etudiant_sign_up'
  end


  devise_for :tuteur_universitaires, controllers: {
    registrations: "tuteur_universitaires/registrations"
  }

  devise_scope :tuteur_universitaire do
    # get '/sign_in', to: 'devise/sessions#new'
    get 'f5506526-0a7d-40af-a39f-e456e5991564/sign_up', to: 'tuteur_universitaires/registrations#new'
  end


  devise_for :responsable_stages, controllers: {
    registrations: "responsable_stages/registrations"
  }

  devise_scope :responsable_stage do
    # get '/sign_in', to: 'devise/sessions#new'
    get '505cccad-922c-4251-bae6-55c5f91df05b/sign_up', to: 'responsable_stages/registrations#new'
  end


  # Require a root to for devise
  root to: 'static#index'

  get '/static', to: 'static#index'
  post '/fiche_stages/csend', to: 'fiche_stages#csend'
  patch '/fiche_stages/:id/usend', to: 'fiche_stages#usend', as: :fiche_stages_usend
  get '/fiche_stages/:id/validate', to: 'fiche_stages#validate', as: :fiche_stages_validate

  patch '/fiche_stages/:id/vyes', to: 'fiche_stages#vyes', as: :fiche_stages_vyes
  patch '/fiche_stages/:id/vno', to: 'fiche_stages#vno', as: :fiche_stages_vno

  resources :fiche_stages, except: [:destroy, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html





  # Contrôleur EntreprisesController
  resources :entreprises

  # Contrôleur TuteurUniversitaireController
  resources :tuteur_universitaires



  # Contrôleur StaticController
  get '/static', to: 'static#index'

  get '/evaluation', to: 'evaluations#evaluation'
  get '/evaluationtemplate', to: 'evaluations#template'
  get '/notationtemplate', to: 'notations#template'
  post '/evaluation/save/(:id)', to: 'evaluations#save'
  get '/evaluation/edit/(:id)', to: 'evaluations#editEvaluation'
  get '/evaluation/view/(:id)', to: 'evaluations#viewEvaluation'
  get '/tableaudebord', to: 'tableau_de_bord#tableauDeBord'
  get '/menuetudiant', to: 'menu#menuEtudiant'
  get '/menurespstage', to: 'menu#menuRespStage'
  get '/menu', to: 'menu#redirection'
  get '/notation/(:id)', to: 'notations#notation'
  get '/notation/view/(:id)', to: 'notations#viewNotation'
  post '/notation/save', to: 'notations#saveNotation'
  get '/evolution', to: 'evolutions#evolution'
  get '/statistiques', to: 'statistiques#statistiques'
  get '/tableEtudiant', to: 'table_etudiant#tableEtudiant'
  resources :ge_formats
  resources :notation_formats
end

app/models/fiche_stage.rb
class FicheStage < ApplicationRecord
  #belongs_to :formation

  validates :titre, presence: true
  validates :date_debut, presence: true
  validates :date_fin, presence: true

  validates :poste, presence: true
  validates :taches, presence: true
  validates :technologies, presence: true

  validates :contact_nom, presence: true
  validates :contact_prenom, presence: true
  validates :contact_poste, presence: true

  validates :tuteur_nom, presence: true
  validates :tuteur_prenom, presence: true
  validates :tuteur_fonction, presence: true
  validates :tuteur_telephone, presence: true
  validates :tuteur_email, presence: true

  validates :entreprise_nom, presence: true
  validates :entreprise_cp, presence: true
  validates :entreprise_ville, presence: true
  validates :entreprise_pays, presence: true

end

app/controllers/fiche_stages_controller.rb
class FicheStagesController < ApplicationController
  def index
    @fichestage = FicheStage.all
    @fichestage_todo = FicheStage.where(statut: "EN_ATTENTE_DE_VALIDATION")
    @fichestage_draft = FicheStage.where(statut: "BROUILLON")
  end

  def show
    @fichestage = FicheStage.find(params[:id])
  end

  def new
    @fichestage = FicheStage.new
  end

  def create
    @fichestage = FicheStage.new(fiche_stage_params)
    @fichestage.statut = "BROUILLON"
    @fichestage.etudiant_id = current_etudiant.id

    if @fichestage.save
      redirect_to @fichestage
    else
      render :new
    end
  end

  def csend
    @fichestage = FicheStage.new(fiche_stage_params)
    @fichestage.statut = "EN_ATTENTE_DE_VALIDATION"
    @fichestage.etudiant_id = current_etudiant.id

    if @fichestage.save
      redirect_to @fichestage
    else
      render :new
    end
  end

  def edit
    @fichestage = FicheStage.find(params[:id])
  end

  def update
    @fichestage = FicheStage.find(params[:id])
    if @fichestage.statut == "REFUSEE"
      @fichestage.statut = "BROUILLON"
    end

    if @fichestage.update(fiche_stage_params)
      redirect_to @fichestage
    else
      render :show
    end
  end

  def usend
    @fichestage = FicheStage.find(params[:id])

    if @fichestage.update(statut: "EN_ATTENTE_DE_VALIDATION")
      redirect_to @fichestage
    else
      render :show
    end
  end

  def validate
    @fichestage = FicheStage.find(params[:id])
  end

  def vyes
    @fichestage = FicheStage.find(params[:id])
    @fichestage.statut = "VALIDEE"

    if @fichestage.update(fiche_stage_params)
      redirect_to @fichestage
    else
      render :validate
    end
  end

  def vno
    @fichestage = FicheStage.find(params[:id])
    @fichestage.statut = "REFUSEE"

    if @fichestage.update(fiche_stage_params)
      redirect_to @fichestage
    else
      render :validate
    end
  end

  private
  def fiche_stage_params
    params.require(:fiche_stage).permit(
      :titre, :type_stage, :mention, :date_debut, :date_fin,
      :poste, :taches, :technologies, :contact_nom, :contact_prenom, :contact_poste,
      :tuteur_nom, :tuteur_prenom, :tuteur_fonction, :tuteur_telephone, :tuteur_email,
      :entreprise_nom, :entreprise_siren, :entreprise_cp, :entreprise_ville, :entreprise_pays, :commentaire_validation)
  end

  def destroy
    #@fichestage = fiche_stages.all
  end
end

app/helpers/fiche_stages_helper.rb
module FicheStagesHelper
end

app/views/fiche_stages/index.html.erb
<div class="bandeauSuperieur d-flex justify-content-center">
  <span class="mx-4 uppercase font-bold">Fiches de stage</span>
</div>
<ul>
  <% @fichestage.each do |fichestage| %>
    <li>
      Fiche n°<%= fichestage.id %> - <%= link_to fichestage.titre, fiche_stage_path(fichestage) %>
    </li>
  <% end %>
</ul>

<% @fichestage_todo.each do |fstd| %>
  Fiche n°<%= fstd.id %> - <%= link_to fstd.titre, fiche_stages_validate_path(fstd) %>
<% end %>
<% @fichestage_draft.each do |fsd| %>
  <%= fsd.id %>
<% end %>

<br/><br/>
<div class="d-flex justify-content-center m-2 pt-5">
  <button class="btn btn-square btn-sm mx-3"><%= link_to "Nouvelle fiche de stage", new_fiche_stage_path %></button>
</div>

app/views/fiche_stages/new.html.erb
<div class="bandeauSuperieur d-flex justify-content-center">
  <span class="mx-4 uppercase font-bold">Nouvelle fiche de stage</span>
</div>
<br/><br/>

<div class="content">
  <%= form_with model: @fichestage do |form| %>
  <div class="row">
    <div class="col-6 vertical-line">

      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <h2>Informations Générales</h2>
          <div>
            <div class="full-field">
              <%= form.label :titre, "Titre de la fiche de stage" %>
              <%= form.text_field :titre %>
            </div>
            <br/>
            <div class="row">
              <div class="col-6 half-field">
                <%= form.label :mention %>
                <%= form.select :mention, ["L3","M1", "M2"] %>
              </div>
              <div class="col-6 half-field">
                <%= form.label :type_stage %><br>
                <%= form.select :type_stage, ["ALTERNANCE","STAGE"] %>
              </div>
            </div>
            <br/>
            <div class="row">
              <div class="col-6 half-field">
                <%= form.label :date_debut %>
                <%= form.date_field :date_debut %>
              </div>
              <div class="col-6 half-field">
                <%= form.label :date_fin %>
                <%= form.date_field :date_fin %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
      <br/><br/><br/>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <h2>Informations sur le Poste</h2>
          <div>
            <div class="full-field">
              <%= form.label :poste, "Intitulé du poste" %><br>
              <%= form.text_field :poste %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :taches, "Sujet de stage" %><br>
              <%= form.text_area :taches %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :technologies, "Technologies employées" %><br>
              <%= form.text_area :technologies %>
            </div>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
      <br/><br/><br/>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <h2>Informations sur le Tuteur</h2>
          <div>
            <div class="full-field">
              <%= form.label :tuteur_nom, "Nom" %><br>
              <%= form.text_field :tuteur_nom %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :tuteur_prenom, "Prénom" %><br>
              <%= form.text_field :tuteur_prenom %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :tuteur_fonction, "Fonction" %><br>
              <%= form.text_field :tuteur_fonction %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :tuteur_telephone, "Téléphone" %><br>
              <%= form.telephone_field :tuteur_telephone %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :tuteur_email, "Email" %><br>
              <%= form.text_field :tuteur_email %>
            </div>
            <br>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
    </div>

    <div class="col-6">
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <h2>Informations sur l'entreprise</h2>
          <div>
            <div class="full-field">
              <%= form.label :entreprise_nom, "Raison sociale de l'entreprise" %><br>
              <%= form.text_field :entreprise_nom %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :entreprise_siren, "Numéro SIREN de l'entreprise" %><br>
              <%= form.text_field :entreprise_siren %>
            </div>
            <br/>
            <div class="row">
              <div class="col-6 half-field">
                <%= form.label :entreprise_cp, "Code Postal" %><br>
                <%= form.text_field :entreprise_cp %>
              </div>
              <div class="col-6 half-field">
                <%= form.label :entreprise_ville, "Ville" %><br>
                <%= form.text_field :entreprise_ville %>
              </div>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :entreprise_pays, "Pays" %><br>
              <%= form.telephone_field :entreprise_pays %>
            </div>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
      <br/><br/><br/>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <h2>Informations sur le signataire</h2>
          <div>
            <div class="full-field">
              <%= form.label :contact_nom, "Nom" %><br>
              <%= form.text_field :contact_nom %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :contact_prenom, "Prénom" %><br>
              <%= form.text_field :contact_prenom %>
            </div>
            <br/>
            <div class="full-field">
              <%= form.label :contact_poste, "Fonction" %><br>
              <%= form.text_field :contact_poste %>
            </div>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
      <br/><br/><br/>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <% unless @fichestage.errors.full_messages.blank? %>
            <h2> Erreurs sur le formulaire</h2>
            <%= @fichestage.errors.full_messages %>
          <% end %>
        </div>
      <div class="col-2"></div>
      </div>
      <br/><br/><br/>
      <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
          <div class="row">
            <div class="col-4">
              <%= form.submit "Enregistrer", formaction: fiche_stages_path, class: "btn btn-primary btn-round" %>
            </div>
            <div class="col-4">
              <%= form.submit "Envoyer", formaction: fiche_stages_csend_path, class: "btn btn-primary btn-round" %>
            </div>
            <div class="col-4 btn-end">
              <%= link_to "Annuler", :back, class: "btn btn-primary btn-round"%>
            </div>
          </div>
        </div>
        <div class="col-1"></div>
      </div>

    </div>

  </div>
  <% end %>
</div>

app/views/fiche_stages/show.html.erb
<div class="row fstitle">
  <div class="col-3"></div>
  <div class="col-6">
    <h1><%= @fichestage.titre %></h1>
  </div>
  <div class="col-3 statcre">
    <%= @fichestage.statut %> <br/>
    Crée le <%= @fichestage.created_at.strftime('%d/%m/%Y') %>
  </div>

</div>

<br/><br/>

<div class="content">
  <%= form_with model: @fichestage do |form| %>
      <div class="row <%=  'reado' if (@fichestage.statut == 'EN_ATTENTE_DE_VALIDATION') || (@fichestage.statut == 'VALIDEE') %>">
        <div class="col-6 vertical-line">

          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <h2>Informations Générales</h2>
              <div>
                <div class="full-field">
                  <%= form.label :titre, "Titre de la fiche de stage" %>
                  <%= form.text_field :titre %>
                </div>
                <br/>
                <div class="row">
                  <div class="col-6 half-field">
                    <%= form.label :mention %>
                    <%= form.select :mention, ["L3","M1", "M2"] %>
                  </div>
                  <div class="col-6 half-field">
                    <%= form.label :type_stage %><br>
                    <%= form.select :type_stage, ["ALTERNANCE","STAGE"] %>
                  </div>
                </div>
                <br/>
                <div class="row">
                  <div class="col-6 half-field">
                    <%= form.label :date_debut %>
                    <%= form.date_field :date_debut %>
                  </div>
                  <div class="col-6 half-field">
                    <%= form.label :date_fin %>
                    <%= form.date_field :date_fin %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-2"></div>
          </div>
          <br/><br/><br/>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <h2>Informations sur le Poste</h2>
              <div>
                <div class="full-field">
                  <%= form.label :poste, "Intitulé du poste" %><br>
                  <%= form.text_field :poste %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :taches, "Sujet de stage" %><br>
                  <%= form.text_area :taches %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :technologies, "Technologies employées" %><br>
                  <%= form.text_area :technologies %>
                </div>
              </div>
            </div>
            <div class="col-2"></div>
          </div>
          <br/><br/><br/>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <h2>Informations sur le Tuteur</h2>
              <div>
                <div class="full-field">
                  <%= form.label :tuteur_nom, "Nom" %><br>
                  <%= form.text_field :tuteur_nom %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :tuteur_prenom, "Prénom" %><br>
                  <%= form.text_field :tuteur_prenom %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :tuteur_fonction, "Fonction" %><br>
                  <%= form.text_field :tuteur_fonction %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :tuteur_telephone, "Téléphone" %><br>
                  <%= form.telephone_field :tuteur_telephone %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :tuteur_email, "Email" %><br>
                  <%= form.text_field :tuteur_email %>
                </div>

              </div>
            </div>
            <div class="col-2"></div>
          </div>
        </div>

        <div class="col-6">
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <h2>Informations sur l'entreprise</h2>
              <div>
                <div class="full-field">
                  <%= form.label :entreprise_nom, "Raison sociale de l'entreprise" %><br>
                  <%= form.text_field :entreprise_nom %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :entreprise_siren, "Numéro SIREN de l'entreprise" %><br>
                  <%= form.text_field :entreprise_siren %>
                </div>
                <br/>
                <div class="row">
                  <div class="col-6 half-field">
                    <%= form.label :entreprise_cp, "Code Postal" %><br>
                    <%= form.text_field :entreprise_cp %>
                  </div>
                  <div class="col-6 half-field">
                    <%= form.label :entreprise_ville, "Ville" %><br>
                    <%= form.text_field :entreprise_ville %>
                  </div>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :entreprise_pays, "Pays" %><br>
                  <%= form.telephone_field :entreprise_pays %>
                </div>
              </div>
            </div>
            <div class="col-2"></div>
          </div>
          <br/><br/><br/>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <h2>Informations sur le signataire</h2>
              <div>
                <div class="full-field">
                  <%= form.label :contact_nom, "Nom" %><br>
                  <%= form.text_field :contact_nom %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :contact_prenom, "Prénom" %><br>
                  <%= form.text_field :contact_prenom %>
                </div>
                <br/>
                <div class="full-field">
                  <%= form.label :contact_poste, "Fonction" %><br>
                  <%= form.text_field :contact_poste %>
                </div>
              </div>
            </div>
            <div class="col-2"></div>
          </div>
          <br/><br/><br/>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
              <% unless @fichestage.errors.full_messages.blank? %>
                <h2> Erreurs sur le formulaire</h2>
                <%= @fichestage.errors.full_messages %>
              <% end %>
              <% unless @fichestage.commentaire_validation.nil? %>
                <h2>Commentaires de validation</h2>
                <div>
                  <div class="full-field reado">
                    <%= form.label :commentaire_validation, "Commentaires de validation" %><br>
                    <%= form.text_area :commentaire_validation %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="col-2"></div>
          </div>
          <br/><br/><br/>
          <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
              <div class="row">
                <div class="col-4">
                  <%= form.submit "Modifier", formaction: fiche_stage_path(@fichestage), class: "btn btn-primary btn-round" %>
                </div>
                <div class="col-4">
                  <%= form.submit "Envoyer", formaction: fiche_stages_usend_path(@fichestage), class: "btn btn-primary btn-round" %>
                </div>
                <div class="col-4">
                  <%= link_to "Annuler", :back, class: "btn btn-primary btn-round" %>
                </div>
              </div>
            </div>
            <div class="col-1"></div>
          </div>

        </div>

      </div>
  <% end %>
</div>

app/views/fiche_stages/validate.html.erb
<div class="row fstitle">
  <div class="col-3"></div>
  <div class="col-6">
    <h1><%= @fichestage.titre %></h1>
  </div>
  <div class="col-3 statcre">
    <%= @fichestage.statut %> <br/>
    Crée le <%= @fichestage.created_at.strftime('%d/%m/%Y') %>
  </div>

</div>

<br/><br/>

<div class="content">
  <%= form_with model: @fichestage do |form| %>
    <div class="row reado">
      <div class="col-6 vertical-line">

        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Informations Générales</h2>
            <div>
              <div class="full-field">
                <%= form.label :titre, "Titre de la fiche de stage" %>
                <%= form.text_field :titre %>
              </div>
              <br/>
              <div class="row">
                <div class="col-6 half-field">
                  <%= form.label :mention %>
                  <%= form.select :mention, ["L3","M1", "M2"] %>
                </div>
                <div class="col-6 half-field">
                  <%= form.label :type_stage %><br>
                  <%= form.select :type_stage, ["ALTERNANCE","STAGE"] %>
                </div>
              </div>
              <br/>
              <div class="row">
                <div class="col-6 half-field">
                  <%= form.label :date_debut %>
                  <%= form.date_field :date_debut %>
                </div>
                <div class="col-6 half-field">
                  <%= form.label :date_fin %>
                  <%= form.date_field :date_fin %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-2"></div>
        </div>
        <br/><br/><br/>
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Informations sur le Poste</h2>
            <div>
              <div class="full-field">
                <%= form.label :poste, "Intitulé du poste" %><br>
                <%= form.text_field :poste %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :taches, "Sujet de stage" %><br>
                <%= form.text_area :taches %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :technologies, "Technologies employées" %><br>
                <%= form.text_area :technologies %>
              </div>
            </div>
          </div>
          <div class="col-2"></div>
        </div>
        <br/><br/><br/>
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Informations sur le Tuteur</h2>
            <div>
              <div class="full-field">
                <%= form.label :tuteur_nom, "Nom" %><br>
                <%= form.text_field :tuteur_nom %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :tuteur_prenom, "Prénom" %><br>
                <%= form.text_field :tuteur_prenom %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :tuteur_fonction, "Fonction" %><br>
                <%= form.text_field :tuteur_fonction %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :tuteur_telephone, "Téléphone" %><br>
                <%= form.telephone_field :tuteur_telephone %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :tuteur_email, "Email" %><br>
                <%= form.text_field :tuteur_email %>
              </div>

            </div>
          </div>
          <div class="col-2"></div>
        </div>
      </div>

      <div class="col-6">
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Informations sur l'entreprise</h2>
            <div>
              <div class="full-field">
                <%= form.label :entreprise_nom, "Raison sociale de l'entreprise" %><br>
                <%= form.text_field :entreprise_nom %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :entreprise_siren, "Numéro SIREN de l'entreprise" %><br>
                <%= form.text_field :entreprise_siren %>
              </div>
              <br/>
              <div class="row">
                <div class="col-6 half-field">
                  <%= form.label :entreprise_cp, "Code Postal" %><br>
                  <%= form.text_field :entreprise_cp %>
                </div>
                <div class="col-6 half-field">
                  <%= form.label :entreprise_ville, "Ville" %><br>
                  <%= form.text_field :entreprise_ville %>
                </div>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :entreprise_pays, "Pays" %><br>
                <%= form.telephone_field :entreprise_pays %>
              </div>
            </div>
          </div>
          <div class="col-2"></div>
        </div>
        <br/><br/><br/>
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Informations sur le signataire</h2>
            <div>
              <div class="full-field">
                <%= form.label :contact_nom, "Nom" %><br>
                <%= form.text_field :contact_nom %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :contact_prenom, "Prénom" %><br>
                <%= form.text_field :contact_prenom %>
              </div>
              <br/>
              <div class="full-field">
                <%= form.label :contact_poste, "Fonction" %><br>
                <%= form.text_field :contact_poste %>
              </div>
            </div>
          </div>
          <div class="col-2"></div>
        </div>
        <br/><br/><br/>
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <h2>Commentaires de validation</h2>
            <div>
              <div class="full-field noreado">
                <%= form.label :commentaire_validation, "Commentaires de validation" %><br>
                <%= form.text_area :commentaire_validation %>
              </div>
            </div>
          </div>
          <div class="col-2"></div>
        </div>
        <br/><br/><br/>
        <div class="row">
          <div class="col-1"></div>
          <div class="col-10">
            <div class="row">
              <div class="col-4 noreado">
                <%= form.submit "Valider", formaction: fiche_stages_vyes_path(@fichestage), class: "btn btn-primary btn-round" %>
              </div>
              <div class="col-4 noreado">
                <%= form.submit "Refuser", formaction: fiche_stages_vno_path(@fichestage), class: "btn btn-primary btn-round" %>
              </div>
              <div class="col-4 btn-end">
                <%= link_to "Annuler", :back, class: "btn btn-primary btn-round" %>
              </div>
            </div>
          </div>
          <div class="col-1"></div>
        </div>

      </div>

    </div>
  <% end %>
</div>