config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#home'


  # Ressources Promotions
  #
  # Contrôleur : PromotionsController (app/controllers/promotions_controller)
  #
  # Routes :
  #
  resources :promotions do
    member do
      put 'close', to: 'promotions#close'     # Route de clôture de promotion
    end
  end


  # Ressources Formations
  #
  # Contrôleur : FormationsController (app/controllers/formations_controller)
  #
  # Routes :
  #
  resources :formations do
    member do
      get 'next', to: 'formations#next'             # Route pour sélectionner les étudiants à faire passer à la promotion suivante
      post 'transfert', to: 'formations#transfert'  # Route réalisant le transfert des étudiants à la promotion suivante
    end
  end


  # Ressources Etudiants
  #
  # Contrôleur : EtudiantsController (app/controllers/etudiants_controller)
  #
  # Routes :
  #       etudiants GET    /etudiants(.:format)                                    etudiants#index
  #                 POST   /etudiants(.:format)                                    etudiants#create
  #    new_etudiant GET    /etudiants/new(.:format)                                etudiants#new
  #   edit_etudiant GET    /etudiants/:id/edit(.:format)                           etudiants#edit
  #        etudiant GET    /etudiants/:id(.:format)                                etudiants#show
  #                 PATCH  /etudiants/:id(.:format)                                etudiants#update
  #                 PUT    /etudiants/:id(.:format)                                etudiants#update
  #                 DELETE /etudiants/:id(.:format)                                etudiants#destroy
  #
  resources :etudiants


  # Confiugration des routes pour Devise
  #
  # Documentation : https://github.com/heartcombo/devise#
  #
  # 3 modèles :
  #   - Etudiants                     :etudiants
  #   - Tuteurs universitaires        :tuteur_universitaires
  #   - Responsable des stages        :responsable_stages
  #
  devise_for :etudiants,
             path: '/auth',                                 # Préfixage des routes avec '/auth'
             controllers: {
               # Surcharge du contrôleur de registration de devise par le contrôleur Etudiants::RegistrationsController
               registrations: "etudiants/registrations"
             }

  devise_scope :etudiant do
    # Génération d'une route permettant l'inscription des étudiants
    get '4d6a8d14-ef57-4da8-908d-5b3388bfdf48/sign_up', to: 'etudiants/registrations#new', :as => 'guid_etudiant_sign_up'
  end


  devise_for :tuteur_universitaires, controllers: {
    registrations: "tuteur_universitaires/registrations"
  }

  devise_scope :tuteur_universitaire do
    # get '/sign_in', to: 'devise/sessions#new'
    get 'f5506526-0a7d-40af-a39f-e456e5991564/sign_up', to: 'tuteur_universitaires/registrations#new'
  end


  devise_for :responsable_stages, controllers: {
    registrations: "responsable_stages/registrations"
  }

  devise_scope :responsable_stage do
    # get '/sign_in', to: 'devise/sessions#new'
    get '505cccad-922c-4251-bae6-55c5f91df05b/sign_up', to: 'responsable_stages/registrations#new'
  end


  # Require a root to for devise
  root to: 'static#index'

  get '/static', to: 'static#index'
  post '/fiche_stages/csend', to: 'fiche_stages#csend'
  patch '/fiche_stages/:id/usend', to: 'fiche_stages#usend', as: :fiche_stages_usend
  get '/fiche_stages/:id/validate', to: 'fiche_stages#validate', as: :fiche_stages_validate

  patch '/fiche_stages/:id/vyes', to: 'fiche_stages#vyes', as: :fiche_stages_vyes
  patch '/fiche_stages/:id/vno', to: 'fiche_stages#vno', as: :fiche_stages_vno

  resources :fiche_stages, except: [:destroy, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html





  # Contrôleur EntreprisesController
  resources :entreprises

  # Contrôleur TuteurUniversitaireController
  resources :tuteur_universitaires



  # Contrôleur StaticController
  get '/static', to: 'static#index'

  get '/evaluation', to: 'evaluations#evaluation'
  get '/evaluationtemplate', to: 'evaluations#template'
  get '/notationtemplate', to: 'notations#template'
  post '/evaluation/save/(:id)', to: 'evaluations#save'
  get '/evaluation/edit/(:id)', to: 'evaluations#editEvaluation'
  get '/evaluation/view/(:id)', to: 'evaluations#viewEvaluation'
  get '/tableaudebord', to: 'tableau_de_bord#tableauDeBord'
  get '/menuetudiant', to: 'menu#menuEtudiant'
  get '/menurespstage', to: 'menu#menuRespStage'
  get '/menu', to: 'menu#redirection'
  get '/notation/(:id)', to: 'notations#notation'
  get '/notation/view/(:id)', to: 'notations#viewNotation'
  post '/notation/save', to: 'notations#saveNotation'
  get '/evolution', to: 'evolutions#evolution'
  get '/statistiques', to: 'statistiques#statistiques'
  get '/tableEtudiant', to: 'table_etudiant#tableEtudiant'
  resources :ge_formats
  resources :notation_formats
end

app/controllers/tableau_de_bord_controller.rb
class TableauDeBordController < ApplicationController
  def tableauDeBord
    require 'json'
    if !tuteur_universitaire_signed_in? && !responsable_stage_signed_in?
      redirect_to("/")
    else
      if tuteur_universitaire_signed_in?
        idTuteur = current_tuteur_universitaire.id
      else
        if responsable_stage_signed_in?
          idTuteur = current_responsable_stage.id
        end
      end

      require 'json'

      @filtre = 'tout'
      url = request.original_url
      if url.include? "filtre=" then
        uri    = URI.parse(url)
        params = CGI.parse(uri.query)
        @filtre = params['filtre'][0].to_s
      end

      if @filtre == 'tout' then
        if tuteur_universitaire_signed_in? then
          sqlStage =
            " SELECT stages.id, sujet, type_stage, nom, prenom, mention, raison_sociale " +
              " FROM stages, formations, promotions, etudiants, entreprises " +
              " WHERE tuteur_universitaire_id = " + idTuteur.to_s +
              " AND stages.formation_id = formations.id" +
              " AND formations.promotion_id = promotions.id" +
              " AND stages.etudiant_id = etudiants.id" +
              " AND stages.entreprise_id = entreprises.id " +
              " AND promotions.id = (SELECT MAX(promotions.id) FROM promotions)"
        else
          sqlStage =
            " SELECT stages.id, sujet, type_stage, nom, prenom, mention, raison_sociale " +
              " FROM stages, formations, promotions, etudiants, entreprises " +
              " WHERE stages.formation_id = formations.id" +
              " AND formations.promotion_id = promotions.id" +
              " AND stages.etudiant_id = etudiants.id" +
              " AND stages.entreprise_id = entreprises.id " +
              " AND promotions.id = (SELECT MAX(promotions.id) FROM promotions)"
        end
      else
        if tuteur_universitaire_signed_in? then
          sqlStage =
            " SELECT stages.id, sujet, type_stage, nom, prenom, mention, raison_sociale " +
              " FROM stages, formations, promotions, etudiants, entreprises " +
              " WHERE tuteur_universitaire_id = " + idTuteur.to_s +
              " AND stages.formation_id = formations.id" +
              " AND formations.promotion_id = promotions.id" +
              " AND stages.etudiant_id = etudiants.id" +
              " AND stages.entreprise_id = entreprises.id " +
              " AND formations.mention = '" + @filtre + "'" +
              " AND promotions.id = (SELECT MAX(promotions.id) FROM promotions)"
        else
          sqlStage =
            " SELECT stages.id, sujet, type_stage, nom, prenom, mention, raison_sociale " +
              " FROM stages, formations, promotions, etudiants, entreprises " +
              " WHERE stages.formation_id = formations.id" +
              " AND formations.promotion_id = promotions.id" +
              " AND stages.etudiant_id = etudiants.id" +
              " AND stages.entreprise_id = entreprises.id " +
              " AND formations.mention = '" + @filtre + "'" +
              " AND promotions.id = (SELECT MAX(promotions.id) FROM promotions)"
        end
      end

      @stages = ActiveRecord::Base.connection.select_rows(sqlStage)
      i = 0
      text = '{"etudiants":['

      @stages.each do |stage|
        autoEval  = 'null'
        autoEvalFinal = 'null'
        grille = 'null'
        grilleFinal = 'null'

        sqleval =
          "SELECT id,
        COUNT(CASE WHEN auto_evaluation = 1 THEN (CASE WHEN finale = 0 THEN id END)END) as autoEval,
        COUNT(CASE WHEN auto_evaluation = 1 THEN (CASE WHEN finale = 1 THEN id END)END) as autoEvalFinal,
        COUNT(CASE WHEN auto_evaluation = 0 THEN (CASE WHEN finale = 0 THEN id END)END) as grille,
        COUNT(CASE WHEN auto_evaluation = 0 THEN (CASE WHEN finale = 1 THEN id END)END) as grilleFinal
        FROM evaluations
        WHERE evaluations.stage_id = " + stage[0].to_s + "
        AND evaluations.rempli = 1"
        eval = ActiveRecord::Base.connection.select_rows(sqleval)

        sqlautoeval =
          "SELECT id
        FROM evaluations
        WHERE evaluations.stage_id = " + stage[0].to_s + "
        AND evaluations.auto_evaluation = 1
        AND evaluations.finale = 0"
        resautoeval = ActiveRecord::Base.connection.select_rows(sqlautoeval)
        idautoeval = 'null'
        if resautoeval.count != 0
          idautoeval = resautoeval[0][0].to_s
        end

        sqleval =
          "SELECT id
        FROM evaluations
        WHERE evaluations.stage_id = " + stage[0].to_s + "
        AND evaluations.auto_evaluation = 0
        AND evaluations.finale = 0"
        reseval = ActiveRecord::Base.connection.select_rows(sqleval)
        ideval = 'null'
        if reseval.count != 0
          ideval = reseval[0][0].to_s
        end

        sqlautoevalfinale =
          "SELECT id
        FROM evaluations
        WHERE evaluations.stage_id = " + stage[0].to_s + "
        AND evaluations.auto_evaluation = 1
        AND evaluations.finale = 1"
        resautoevalfinale = ActiveRecord::Base.connection.select_rows(sqlautoevalfinale)
        idautoevalfinale = 'null'
        if resautoevalfinale.count != 0
          idautoevalfinale = resautoevalfinale[0][0].to_s
        end

        sqlevalfinale =
          "SELECT id
        FROM evaluations
        WHERE evaluations.stage_id = " + stage[0].to_s + "
        AND evaluations.auto_evaluation = 0
        AND evaluations.finale = 1"
        resevalfinale = ActiveRecord::Base.connection.select_rows(sqlevalfinale)
        idevalfinale = 'null'
        if resevalfinale.count != 0
          idevalfinale = resevalfinale[0][0].to_s
        end

        sqlnote =
          "SELECT id
        FROM notations
        WHERE notations.stage_id = " + stage[0].to_s
        resnote = ActiveRecord::Base.connection.select_rows(sqlnote)
        idnote = 'null'
        if resnote.count != 0
          idnote = resnote[0][0].to_s
        end

        if eval.count != 0
          if (eval[0][0].to_s != 0)
            autoEval  = eval[0][1].to_s
          end
          if (eval[0][1].to_s != 0)
            autoEvalFinal = eval[0][2].to_s
          end
          if (eval[0][2].to_s != 0)
            grille = eval[0][3].to_s
          end
          if (eval[0][3] != 0)
            grilleFinal = eval[0][4].to_s
          end
        end

        sqlnotation = "SELECT COUNT(*) as note FROM notations WHERE notations.stage_id = " + stage[0].to_s + " AND notations.rempli = 1"
        notation = ActiveRecord::Base.connection.select_rows(sqlnotation)

        if notation.count == 0
          notation = 'null'
        else
          notation = notation[0][0].to_s
        end
        if(i>0)
          text += ','
        end
        text += '{"nom": "'+stage[3] +' '+ stage[4] +'","promotion": "'+stage[5]+'", "entreprise": "'+stage[6]+'", "type": "'+stage[2]+'", "autoevaluation": '+autoEval+', "grilleevaluation": '+grille+', "autoevaluationfinale": '+autoEvalFinal+', "grilleevaluationfinale": '+grilleFinal+',  "note": '+notation+', "idautoevaluation": '+idautoeval+', "idevaluation": '+ideval+', "idautoevaluationfinale": '+idautoevalfinale+', "idevaluationfinale": '+idevalfinale+', "idnote": '+idnote+'}'
        i += 1
      end
      text += ']}'

      @data = JSON.parse(text)
    end
  end
end

app/views/tableau_de_bord/tableauDeBord.html.erb
<%= stylesheet_link_tag "tableauDeBord" %>

<div class="bandeauSuperieur d-flex justify-content-center">
  <span class="mx-4 uppercase font-bold">Tableau de bord</span>
</div>

<div class="container drop py-3">
  <select class="dropdown" name="promo" required onChange="window.location.href=this.value">

    <% if @filtre == 'tout' then %>
      <option selected class="dropdown-item" value="./tableaudebord">Toutes les promotions</option>
    <% else %>
      <option class="dropdown-item" value="./tableaudebord">Toutes les promotions</option>
    <% end %>
    <% if @filtre == 'L3' then %>
      <option selected class="dropdown-item" value="./tableaudebord?filtre=L3">L3 MIAGE</option>
    <% else %>
      <option class="dropdown-item" value="./tableaudebord?filtre=L3">L3 MIAGE</option>
    <% end %>
    <% if @filtre == 'M1' then %>
      <option selected class="dropdown-item" value="./tableaudebord?filtre=M1">M1 MIAGE</option>
    <% else %>
      <option class="dropdown-item" value="./tableaudebord?filtre=M1">M1 MIAGE</option>
    <% end %>
    <% if @filtre == 'M2' then %>
      <option selected class="dropdown-item" value="./tableaudebord?filtre=M2">M2 MIAGE</option>
    <% else %>
      <option class="dropdown-item" value="./tableaudebord?filtre=M2">M2 MIAGE</option>
    <% end %>

  </select>
</div>

<div class="card-body p-0">
  <% if @data.present? then %>
    <% if @data['etudiants'].length > 0 then %>

      <div class="table-responsive p-2">
        <table class="table table-bordered tableaudebord tableBleu" id="dataTable" width="100%" cellspacing="0" cellpadding="0">
          <thead>
          <tr>
            <th>Etudiant</th>
            <th>Promotion</th>
            <th>Entreprise</th>
            <th>Type</th>
            <th>Auto-évaluation</th>
            <th>Grille d'évaluation</th>
            <th>Auto-évaluation finale</th>
            <th>Grille d'évaluation finale</th>
            <th>Note entreprise</th>
          </tr>
          </thead>
          <tbody>
          <% @data['etudiants'].each do |valueData| %>

            <tr>
              <td>
                <div class="d-flex flex-column justify-content-between">
                  <span><%= valueData['nom'] %></span>
                </div>
              </td>
              <td>
                <div class="d-flex flex-column justify-content-between">
                  <span><%= valueData['promotion'] %></span>
                </div>
              </td>
              <td>
                <div class="d-flex flex-column justify-content-between">
                  <span><%= valueData['entreprise'] %></span>
                </div>
              </td>
              <td>
                <div class="d-flex flex-column justify-content-between">
                  <span><%= valueData['type'] %></span>
                </div>
              </td>

              <td>
                <div class="d-flex flex-column justify-content-between">
                  <% if valueData['idautoevaluation'] == nil then %>
                    <span class="not-completed">Indisponible</span>
                  <% else %>
                    <% if valueData['autoevaluation'] == 1 then %>
                      <span class="completed">Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/view/<%= valueData['idautoevaluation'] %>');">Consulter</button>
                    <% else %>
                      <span class="not-completed">Non Completée</span>
                    <% end %>
                  <% end %>
                </div>
              </td>

              <td>
                <div class="d-flex flex-column justify-content-between">
                  <% if valueData['idevaluation'] == nil then %>
                    <span class="not-completed">Indisponible</span>
                  <% else %>
                    <% if valueData['grilleevaluation'] == 1 then %>
                      <span class="completed">Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/view/<%= valueData['idevaluation'] %>');">Consulter</button>
                    <% else %>
                      <span class="not-completed">Non Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/edit/<%= valueData['idevaluation'] %>');">Remplir</button>
                    <% end %>
                  <% end %>
                </div>
              </td>

              <td>
                <div class="d-flex flex-column justify-content-between">
                  <% if valueData['idautoevaluationfinale'] == nil then %>
                    <span class="not-completed">Indisponible</span>
                  <% else %>
                    <% if valueData['autoevaluationfinale'] == 1 then %>
                      <span class="completed">Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/view/<%= valueData['idautoevaluationfinale'] %>');">Consulter</button>
                    <% else %>
                      <span class="not-completed">Non Completée</span>
                    <% end %>
                  <% end %>
                </div>
              </td>

              <td>
                <div class="d-flex flex-column justify-content-between">
                  <% if valueData['idevaluationfinale'] == nil then %>
                    <span class="not-completed">Indisponible</span>
                  <% else %>
                    <% if valueData['grilleevaluationfinale'] == 1 then %>
                      <span class="completed">Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/view/<%= valueData['idevaluationfinale'] %>');">Consulter</button>
                    <% else %>
                      <span class="not-completed">Non Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./evaluation/edit/<%= valueData['idevaluationfinale'] %>');">Remplir</button>
                    <% end %>
                  <% end %>
                </div>
              </td>

              <td>
                <div class="d-flex flex-column justify-content-between">
                  <% if valueData['idnote'] == nil then %>
                    <span class="not-completed">Indisponible</span>
                  <% else %>
                    <% if valueData['note'] == 1 then %>
                      <span class="completed">Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./notation/view/<%= valueData['idnote'] %>');">Consulter</button>
                    <% else %>
                      <span class="not-completed">Non Completée</span>
                      <button type="button" class="btn btn-round btn-sm px-3 mt-2" onclick="window.location.assign('./notation/<%= valueData['idnote'] %>');">Remplir</button>
                    <% end %>
                  <% end %>
                </div>
              </td>

            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

    <% else %>

      <span class="my-5">Aucun étudiant n'est présent dans cette promotion</span>
      <br><br><br>

    <% end %>
  <% end %>
</div>

<div class="d-flex justify-content-center m-2 pt-5">
  <button class="btn btn-square btn-sm mx-3" onclick="window.open('<%= evaluation_path(format: 'pdf') %>', '_blank');">Télécharger le template grille d'évaluation</button>
</div>